CREATE TABLE IF NOT EXISTS appointments (
  appointment_id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  slot VARCHAR(64) NOT NULL UNIQUE,
  source VARCHAR(64) NOT NULL DEFAULT 'voice_bot',
  status VARCHAR(32) NOT NULL DEFAULT 'confirmed',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
